# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [12]:
import numpy as np

a = np.random.rand(2, 3);

print('list(a): ', list(a),'當Array為多維時，只會轉換第一層為List。')
print('tolist(): ', a.tolist(),'將Array所有元素，傳換為List。')

list(a):  [array([0.80617651, 0.83835758, 0.6028208 ]), array([0.04168256, 0.0789446 , 0.36854676])] 當Array為多維時，只會轉換第一層為List。
tolist():  [[0.8061765098641887, 0.838357580744932, 0.6028208006647999], [0.041682559667693075, 0.07894460043158424, 0.36854675589844543]] 將Array所有元素，傳換為List。


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [22]:
# 記得先 Import 正確的套件
import numpy as np


In [32]:

a = np.random.randint(10, size=6) 
print(a);
print('陣列A有多少維度',a.ndim);
print('陣列A每個維度大小',a.shape);
print('陣列A中有幾個元素',a.size);
print('陣列A中的資料型態',a.dtype);
print('陣列A中每個元素占用的空間',a.itemsize); 
print('陣列A的長度',len(a));
print('陣列A的型別',type(a));

[6 5 9 2 4 5]
陣列A有多少維度 1
陣列A每個維度大小 (6,)
陣列A中有幾個元素 6
陣列A中的資料型態 int32
陣列A中每個元素占用的空間 4
陣列A的長度 6
陣列A的型別 <class 'numpy.ndarray'>


In [34]:
b = np.random.randint(10, size=(3,4)) 

print(b);
print('陣列B有多少維度 : ',b.ndim);
print('陣列B每個維度大小 : ',b.shape);
print('陣列B中有幾個元素 : ',b.size);
print('陣列B中的資料型態 : ',b.dtype);
print('陣列B中每個元素占用的空間 : ',b.itemsize);
print('陣列B的長度',len(b));
print('陣列B的型別',type(b));

[[6 3 9 5]
 [2 9 0 9]
 [5 3 9 2]]
陣列B有多少維度 :  2
陣列B每個維度大小 :  (3, 4)
陣列B中有幾個元素 :  12
陣列B中的資料型態 :  int32
陣列B中每個元素占用的空間 :  4
陣列B的長度 3
陣列B的型別 <class 'numpy.ndarray'>


In [37]:
c = np.random.randint(10, size=(2,3,2)) 

print(c);
print('陣列C有多少維度 : ',c.ndim);
print('陣列C每個維度大小 : ',c.shape);
print('陣列C中有幾個元素 : ',c.size);
print('陣列C中的資料型態 : ',c.dtype);
print('陣列C中每個元素占用的空間 : ',c.itemsize);
print('陣列C的長度',len(c));
print('陣列C的型別',type(c));

[[[6 6]
  [8 8]
  [4 1]]

 [[0 7]
  [4 3]
  [4 2]]]
陣列C有多少維度 :  3
陣列C每個維度大小 :  (2, 3, 2)
陣列C中有幾個元素 :  12
陣列C中的資料型態 :  int32
陣列C中每個元素占用的空間 :  4
陣列C的長度 2
陣列C的型別 <class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [44]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[4, 2, 8, 0, 1, 0]
[4, 2, 8, 0, 1, 0]


In [45]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 7, 2, 9], [8, 1, 4, 7], [6, 7, 5, 3]]
[array([5, 7, 2, 9]), array([8, 1, 4, 7]), array([6, 7, 5, 3])]


In [46]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[4, 5], [6, 3], [0, 1]], [[7, 2], [5, 3], [6, 6]]]
[array([[4, 5],
       [6, 3],
       [0, 1]]), array([[7, 2],
       [5, 3],
       [6, 6]])]


In [50]:
def tolist(iterable):
    return iterable.tolist();

print(tolist(a))
print(tolist(b))
print(tolist(c))

[4, 2, 8, 0, 1, 0]
[[5, 7, 2, 9], [8, 1, 4, 7], [6, 7, 5, 3]]
[[[4, 5], [6, 3], [0, 1]], [[7, 2], [5, 3], [6, 6]]]
